# Generated by Django 4.2.10 on 2024-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('app_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('github_link', models.URLField()),
                ('remark', models.TextField()),
            ],
        ),
    ]
